//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
[assembly: InternalsVisibleTo(@"CrtSmsIntegration.UnitTests")]
